name: Unity License Activation
on:
  workflow_dispatch:

jobs:
  activate:
    name: Request Unity License File
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get Unity License
        uses: game-ci/unity-builder@v4
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: Android
          unityVersion: 2022.3.20f1
          buildMethod: ""
          allowDirtyBuild: true

      - name: Upload license
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Unity_License
          path: |
            /root/.local/share/unity3d/Unity/Unity_lic.ulf
            Unity_v*.ulf
            *.ulf
          retention-days: 1
